import Head from 'next/head'
import { Inter } from 'next/font/google';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import { css } from '@emotion/css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] })

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrowserRouter>
        <Navbar />
        <Routes>
          <Route path="/about" element={<h1>About</h1>} />
          <Route path="/" element={<h1>Home</h1>} />
        </Routes>
      </BrowserRouter>
    </>
  )
}

export default Index;